### ISSUE TITLE
TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by tdhopper** [andyroyle/storm-statsd#1]
Awesome little project, thanks @andyroyle.

After I redeploy my topology, I get this: 

```
TypeError: Cannot read property '0' of undefined
    at decorate (/usr/lib/node_modules/storm-statsd/lib/spouts.js:13:25)
    at /usr/lib/node_modules/storm-statsd/lib/spouts.js:33:20
    at Request._callback (/usr/lib/node_modules/storm-statsd/node_modules/storm-http/storm.js:24:7)
    at Request.self.callback (/usr/lib/node_modules/storm-statsd/node_modules/request/request.js:187:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/usr/lib/node_modules/storm-statsd/node_modules/request/request.js:1048:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/storm-statsd/node_modules/request/request.js:969:12)
/usr/lib/node_modules/storm-statsd/lib/spouts.js:13
  if(!spout.spoutSummary[0]){
```

It recovers after I restart the process. Any idea what causes this?

**Comment by andyroyle** [comment]
thanks for the feedback dude.

Can you tell me what version of storm are you using? and what version of storm-statsd are you using?

**Comment by tdhopper** [comment]
@andyroyle Storm 1.0.2, storm-statsd 2.0.0

**Comment by andyroyle** [comment]
I think it's related to the fact that `"spoutSummary": [..]` array can be empty before the topology has properly started.

I'm not sure if this behaviour changed with `1.x` but I noticed it and added the following [guard-code](https://github.com/andyroyle/storm-statsd/blob/master/lib/spouts.js#L13); unfortunately it may have backfired.

I'll see if i can reproduce. 

It may well be that there are cases when the `spoutSummary` property is missing altogether

**Comment by andyroyle** [comment]
So it seems that in some cases the `boltStats` (and `spoutSummary`) properties will be empty.

Moar guard code needed!

**Comment by andyroyle** [comment]
Published a fix in [v2.0.1](https://www.npmjs.com/package/storm-statsd), should solve the issue.

Let me know 👍
